name: Lighthouse CI with Netlify
on: pull_request
jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install & Build
        run: |
          yarn install
          yarn build
      - name: Wait for the Netlify Preview
        uses: jakepartusch/wait-for-netlify-action@v1
        id: netlify
        with:
          site_name: "automated-a11y-with-lighthouse"
      - name: Audit core URLs on DP
        uses: treosh/lighthouse-ci-action@v10
        with:
          urls: |
            ${{ steps.netlify.outputs.url }}
            ${{ steps.netlify.outputs.url }}/post/
            ${{ steps.netlify.outputs.url }}/topic/
          configPath: "./lighthouserc.json"
          uploadArtifacts: true
